/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class AutoBuildExampleLibrary {
    public static void RunLibraryTest() {
        System.out.println("Hello World from the Auto Builder Script!!");
    }

    public static void SomeOtherMethod() {
        System.out.println("Yes, you have access to this method too :)");
    }
}
